pleasing:
  assets:
    rules_css:
      inputs: 
        - "resources/scss/rules.scss"
      output: "dist/css/rules.css"
    rules_css_min:
      filters: ['minify']
      inputs: 
        - "resources/scss/rules.scss"
      output: "dist/css/rules.min.css"
